# Kintsugi Configuration
version: 1
# Master toggle - set to false to temporarily disable Kintsugi
enabled: false
# Demo password for hackathon
demo_password: "kintsugi-gemini3-demo-2026"
# Clean up .kintsugi folder after PR is created (won't be merged into main)
cleanup_metadata: true

# Branch configuration
branches:
  allow:
    - "main"
    - "master"
    - "kintsugi-fix*"

# Minimal limits - let Kintsugi work freely
limits:
  max_attempts: 10
  max_files_changed: 5
  max_import_depth: 5  # Parse imports up to 5 levels deep


# Security 
security:
  protected_paths:
    - ".github/**"
    - "package.json"
    - "package-lock.json"
  scan_enabled: true
  block_on_critical: true

# AI - Smart mode for full reasoning
ai:
  mode: "smart"
  extra_instructions: |
    This is the Kintsugi Gauntlet stress test.
    Use all available evidence: video, screenshots, and deep code analysis.
    The bugs are intentionally difficult - trust the evidence.

updates:
  mode: transparent  # Show live status on draft PR, use "silent" for no updates